name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.29.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chrome

      - name: Start shopping-store application
        run: |
          echo "üöÄ Starting shopping-store server..."
          chmod +x ./shopping-store-linux-amd64
          nohup ./shopping-store-linux-amd64 > server.log 2>&1 &
          echo "‚è≥ Waiting for server to start..."
          npx wait-on http://localhost:2221
        shell: bash

      - name: Run Playwright tests
        env:
          CI: true
        run: |
          echo "üé≠ Running Playwright tests..."
          npm run test:ci

      - name: Upload Playwright report
        if: always()   # instead of !cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

